# Generated by Django 5.2.8 on 2025-11-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoen_app', '0006_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
