# Generated by Django 5.2.8 on 2025-11-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoen_app', '0007_perfil_avatar_perfil_bio_perfil_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='fecha',
        ),
    ]
