# Generated by Django 5.2.8 on 2025-11-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoen_app', '0008_remove_opinion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='es_cliente',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='es_vendedor',
        ),
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
