# Generated by Django 5.2.8 on 2025-11-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecoen_app",
            "0009_remove_perfil_es_cliente_remove_perfil_es_vendedor_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfil",
            name="rol",
        ),
        migrations.AddField(
            model_name="perfil",
            name="es_cliente",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="perfil",
            name="es_vendedor",
            field=models.BooleanField(default=False),
        ),
    ]
